stages:
  - build

rust-latest:
  stage: build
  image: rust:bullseye
  before_script:
    - apt-get update -yqq
    - apt-get install libgdal-dev gdal-bin -yqq --no-install-recommends build-essential
    - export SQLX_OFFLINE=true
  script:
    - cargo build --verbose --all-features
    - cargo test --verbose --all-features -- --skip minimal_feature_crud --skip edr

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  before_script:
    - apt-get update -yqq
    - apt-get install libgdal-dev gdal-bin -yqq --no-install-recommends build-essential
    - export SQLX_OFFLINE=true
  script:
    - cargo build --verbose --all-features
    - cargo test --verbose --all-features -- --skip minimal_feature_crud --skip edr
  allow_failure: true
