[package]
name = "oapi"
version = "0.1.0"
authors = ["Balthasar Teuscher <balthasar.teuscher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.10.0"
async-std = { version = "1.6.0", features = ["attributes"] }
serde = "1.0.111"
serde_json = "1.0.55"
serde_yaml = "0.8.13"
openapiv3 = "0.3.2"