[package]
name = "ogcapi"
version = "0.1.0"
license = "GPL-3.0-only"
authors = ["Balthasar Teuscher <balthasar.teuscher@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-std = { version = "1.10", optional = true, features = ["attributes"] }
chrono = { version = "0.4", features = ["serde"] }
dotenv = { version = "0.15", optional = true }
env_logger = { version = "0.9", optional = true }
gdal = { version = "0.11.0", optional = true, features = ["bindgen"] }
geo = { version = "0.18", optional = true }
geojson = "0.22"
http = "0.2.6"
log = { version = "0.4", optional = true }
openapiv3 = { version = "1.0.0", optional = true }
osmpbfreader = { version = "0.15", optional = true }
pbr = { version = "1", optional = true }
rink-core = { version = "0.6", optional = true }
serde = "1"
serde_json = "1"
serde_with = { version = "1", features = ["json"] }
serde_yaml = { version = "0.8", optional = true }
sqlx = { version = "0.5", optional = true, features = ["runtime-async-std-rustls", "postgres", "json", "offline", "chrono"] }
structopt = "0.3"
tide = { version = "0.16", optional = true }
url = { version = "2", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
wkb = { version = "0.7", optional = true }

[features]
default = ["common", "server", "sqlx"]
common = []
processes = ["common"]
edr = ["rink-core"]
import = ["gdal", "osmpbfreader", "pbr", "wkb"]
server = ["async-std", "dotenv", "env_logger", "geo", "log", "openapiv3", "serde_yaml", "tide"]
