[package]
name = "ogcapi"
version = "0.1.0"
license = "GPL-3.0-only"
authors = ["Balthasar Teuscher <balthasar.teuscher@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
axum = { version = "0.4.8", optional = true, features = ["headers"] }
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.1.5", features = ["derive", "env"] }
dotenv = { version = "0.15", optional = true }
env_logger = { version = "0.9", optional = true }
gdal = { version = "0.12.0", optional = true, features = ["bindgen"] }
geo = { version = "0.19.0", optional = true }
geojson = "0.22.2"
hyper = { version = "0.14.17", optional = true, features = ["full"] }
http = "0.2.6"
log = { version = "0.4", optional = true }
openapiv3 = { version = "1.0.1", optional = true }
osmpbfreader = { version = "0.15.2", optional = true }
pbr = { version = "1.0.4", optional = true }
rink-core = { version = "0.6.2", optional = true }
serde = "1.0.136"
serde_json = "1.0.79"
serde_with = { version = "1.12.0", features = ["json"] }
serde_yaml = { version = "0.8.23", optional = true }
sqlx = { version = "0.5.11", optional = true, features = ["runtime-tokio-rustls", "postgres", "json", "offline", "chrono"] }
thiserror = "1.0.30"
tokio = { version = "1.17.0", optional = true, features = ["full"] }
tower = { version = "0.4.12", optional = true }
tower-http = { version = "0.2.3", optional = true, features = ["cors", "trace"] }
tracing = { version = "0.1.31", optional = true }
tracing-subscriber = { version="0.3.9", optional = true, features = ["env-filter"] }
url = { version = "2.2.2", features = ["serde"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
wkb = { version = "0.7.1", optional = true }

[dev-dependencies]
serde_qs = "0.8.5"

[features]
default = ["common", "server", "sqlx", "tokio"]
common = []
edr = ["rink-core"]
import = ["gdal", "osmpbfreader", "pbr", "wkb"]
server = ["axum", "dotenv", "env_logger", "geo", "hyper", "log", "openapiv3", "serde_yaml", "tower", "tower-http", "tracing", "tracing-subscriber"]
