[package]
name = "ogcapi"
version = "0.1.0"
license = "GPL-3.0-only"
authors = ["Balthasar Teuscher <balthasar.teuscher@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-std = { version = "1.10", features = ["attributes"] }
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
env_logger = "0.9"
gdal = {version = "0.10.0", features = ["datetime"] }
geo = "0.18"
geojson = "0.22"
log = "0.4"
openapiv3 = "0.5"
osmpbfreader = "0.15"
pbr = "1"
rink-core = "0.6.0"
serde = "1"
serde_json = "1"
serde_with = { version = "1", features = ["json"] }
serde_yaml = "0.8"
sqlx = { version = "0.5", features = ["runtime-async-std-native-tls", "macros", "postgres", "json", "offline", "chrono"] }
structopt = "0.3"
tide = "0.16"
url = { version = "2", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
wkb = "0.7"
