[workspace]

members = [
    "ogcapi",
    "ogcapi-client",
    "ogcapi-drivers",
    "ogcapi-services",
    "ogcapi-types",
]
default-members = ["ogcapi"]

[workspace.package]
license = "MIT OR Apache-2.0"
repository = "https://github.com/georust/ogcapi"
edition = "2021"
rust-version = "1.64" # or greater

[patch.crates-io]
ogcapi-types = { path = "ogcapi-types" }
ogcapi-drivers = { path = "ogcapi-drivers" }
ogcapi-services = { path = "ogcapi-services" }
ogcapi-client = { path = "ogcapi-client" }
