[package]
name = "ogcapi"
version = "0.1.0"
authors = ["Balthasar Teuscher <balthasar.teuscher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.11"
async-std = { version = "1.6", features = ["attributes"] }
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
openapiv3 = "0.3"
geojson = "0.19"
sqlx = { git = "https://github.com/launchbadge/sqlx", features = ["postgres", "json"] }
chrono = { version = "0.4", features = ["serde"] }