[workspace]

members = [
    "ogcapi",
    "ogcapi-client",
    "ogcapi-drivers",
    "ogcapi-services",
    "ogcapi-types",
]
default-members = ["ogcapi"]

[patch.crates-io]
ogcapi-types = { path = "ogcapi-types" }
ogcapi-drivers = { path = "ogcapi-drivers" }
ogcapi-services = { path = "ogcapi-services" }
ogcapi-client = { path = "ogcapi-client" }
