services:
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
  teamengine:
    image: ogccite/ets-ogcapi-features10:latest
    # image: ogccite/ets-ogcapi-edr10:latest
    ports:
      - 8081:8080