[package]
name = "ogcapi-drivers"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[features]
s3 = ["aws-config", "aws-sdk-s3", "aws-types"]
stac = ["ogcapi-types/stac"]
postgres = ["sqlx", "rink-core", "url"]


[dependencies]
anyhow = "1.0.57"
aws-config = { version = "0.12.0", optional = true }
aws-sdk-s3 = { version = "0.12.0", optional = true }
aws-types = { version = "0.12.0", optional = true }
async-trait = "0.1.53"
http = "0.2.7"
rink-core = { version = "0.6.2", optional = true }
serde_json = "1.0.81"
sqlx = { version = "0.5.13", optional = true, features = ["runtime-tokio-rustls", "postgres", "json"] }
tokio = { version = "1.18.2", features = ["full"] }
url = { version = "2.2.2", optional = true }

ogcapi-types = { path = "../ogcapi-types" }
