[package]
name = "ogcapi_drivers"
version = "0.1.0"
license = "GPL-3.0-only"
authors = ["Balthasar Teuscher <balthasar.teuscher@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
sqlx = { version = "0.5.11", features = ["runtime-tokio-rustls", "postgres", "json", "offline", "chrono"] }
url = { version = "2.2.2", features = ["serde"] }

ogcapi_entities = { path="../ogcapi-entities" }
