[package]
name = "ogcapi"
version = "0.1.0"
license = "GPL-3.0-only"
readme = "../README.md"
edition = "2021"

[features]
default = ["serve", "import", "stac"]
import = ["gdal", "geo", "osmpbfreader", "pbr", "sqlx", "wkb"]
serve = ["axum", "ogcapi-services", "ogcapi-services/full"]
stac = ["ogcapi-types/stac", "ogcapi-drivers/stac", "ogcapi-services?/stac", "ogcapi-drivers/s3"]

[dependencies]
anyhow = "1.0.57"
axum = { version = "0.5.6", optional = true, features = ["headers"] }
clap = { version = "3.1.17", features = ["derive", "env"] }
dotenv = { version = "0.15.0" }
gdal = { version = "0.12.0", optional = true, features = ["bindgen"] }
geo = { version = "0.20.1", optional = true }
geojson = "0.22.3"
osmpbfreader = { version = "0.15.2", optional = true }
pbr = { version = "1.0.4", optional = true }
serde = "1.0.137"
serde_json = "1.0.81"
sqlx = { version = "0.5.13", optional = true, features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.18.2", features = ["full"] }
tracing = { version = "0.1.34"}
tracing-subscriber = { version="0.3.11", features = ["env-filter"] }
url = { version = "2.2.2", features = ["serde"] }
wkb = { version = "0.7.1", optional = true }

ogcapi-types = { path = "../ogcapi-types" }
ogcapi-drivers = { path = "../ogcapi-drivers" }
ogcapi-services = { path = "../ogcapi-services", optional = true }
