[package]
name = "ogcapi"
version = "0.1.0"
description = "OGC API building blocks."
license = "MIT OR Apache-2.0"
repository = "https://github.com/camptocamp/ogcapi"
edition = "2021"

[features]
default = ["types", "client", "drivers", "services", "import"]

client = ["ogcapi-client"]
drivers = ["ogcapi-drivers"]
services = ["ogcapi-services", "ogcapi-services/full"]
types = ["ogcapi-types"]

import = ["gdal", "geo", "geojson", "osmpbfreader", "serde", "serde_json", "sqlx", "url", "wkb"]

stac = ["ogcapi-types?/stac", "ogcapi-drivers?/stac", "ogcapi-drivers?/s3", "ogcapi-services?/stac"]

[dependencies]
anyhow = "1.0.65"
clap = { version = "3.2.22", features = ["derive", "env"] }
dotenvy = "0.15.5"
gdal = { version = "0.13.0", optional = true, features = ["bindgen"] }
geo = { version = "0.23.0", optional = true }
geojson = { version = "0.24.0", optional = true, features = ["geo-types"] }
osmpbfreader = { version = "0.15.2", optional = true }
serde = { version = "1.0.145", optional = true }
serde_json = { version = "1.0.85", optional = true }
sqlx = { version = "0.6.2", optional = true, features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.21.1", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
url = { version = "2.3.1", optional = true, features = ["serde"] }
wkb = { version = "0.7.1", optional = true }

ogcapi-types = { version = "0.1.0", optional = true }
ogcapi-drivers = { version = "0.1.3", optional = true }
ogcapi-services = { version = "0.1.2", optional = true }
ogcapi-client = { version = "0.1.0", optional = true }
