[package]
name = "ogcapi-types"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[features]
default = []
edr = []
stac = []

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
geojson = "0.22.4"
serde = "1.0.137"
serde_json = "1.0.81"
serde_repr = "0.1.8"
serde_with = { version = "1.13.0", features = ["json"] }
url = "2.2.2"
