[package]
name = "ogcapi_types"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[features]
default = []
stac = []

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
geojson = "0.22.3"
serde = "1.0.136"
serde_json = "1.0.79"
serde_repr = "0.1.7"
serde_with = { version = "1.13.0", features = ["json"] }
