[package]
name = "ogcapi-client"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[features]
default = []
stac = ["ogcapi-types/stac"]

[dependencies]
geojson = "0.22.4"
once_cell = "1.12.0"
reqwest = { version = "0.11.10", default-features = false, features = ["json", "blocking", "rustls-tls", "hyper-rustls"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_qs = "0.9.2"
thiserror = "1.0.31"
url = { version = "2.2.2", features = ["serde"]}

ogcapi-types = { path = "../ogcapi-types" }