[package]
name = "ogcapi_client"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[features]
default = []
stac = ["ogcapi_types/stac"]

[dependencies]
geojson = "0.22.3"
once_cell = "1.10.0"
reqwest = { version = "0.11.10", default-features = false, features = ["json", "blocking", "rustls-tls", "hyper-rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
serde_qs = "0.9.1"
thiserror = "1.0.30"
url = { version = "2.2.2", features = ["serde"]}

ogcapi_types = { path = "../ogcapi-types" }