[package]
name = "ogcapi-client"
version = "0.1.0"
description = "Client to access OGC API Feature and STAC endpoints."
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
stac = ["ogcapi-types/stac"]

[dependencies]
log = "0.4.17"
geojson = "0.24.0"
once_cell = "1.15.0"
reqwest = { version = "0.11.12", default-features = false, features = ["json", "blocking", "rustls-tls", "hyper-rustls"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
serde_qs = "0.10.1"
thiserror = "1.0.35"
url = { version = "2.3.1", features = ["serde"] }

ogcapi-types = { path = "../ogcapi-types" }
