[package]
name = "ogcapi_services"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"


[dependencies]
anyhow = "1.0.56"
axum = { version = "0.5.3", features = ["headers"] }
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.1.10", features = ["derive", "env"] }
dotenv = "0.15.0"
hyper = { version = "0.14.18", features = ["full"] }
once_cell = "1.10.0"
openapiv3 = "1.0.1"
rink-core = { version = "0.6.2", optional = true }
serde = "1.0.136"
serde_with = "1.12.1"
serde_json = "1.0.79"
serde_yaml = "0.8.23"
serde_qs = "0.9.1"
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "postgres", "json", "chrono"] }
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.2.5", features = ["cors", "trace"] }
tracing = "0.1.34"
tracing-subscriber = { version="0.3.11", features = ["env-filter"] }
url = { version = "2.2.2", features = ["serde"] }
uuid = { version = "1.0.0", features = ["serde", "v4"] }

ogcapi_types = { path = "../ogcapi-types" }
ogcapi_drivers = { path = "../ogcapi-drivers" }

[dev-dependencies]
geojson = "0.22.3"
ogcapi = { path = "../ogcapi" }


[features]
default = ["drivers", "common", "features", "processes", "styles", "tiles", "edr"]
drivers = []
common = []
features = []
processes = []
styles = []
tiles = []
edr = ["rink-core"]