[package]
name = "ogcapi_services"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[features]
default = ["common", "features", "edr", "processes", "styles", "tiles"]
common = []
features = []
edr = ["rink-core"]
processes = []
styles = []
tiles = []

[dependencies]
anyhow = "1.0.57"
axum = { version = "0.5.4", features = ["headers"] }
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.1.14", features = ["derive", "env"] }
dotenv = "0.15.0"
hyper = { version = "0.14.18", features = ["full"] }
once_cell = "1.10.0"
openapiv3 = "1.0.1"
rink-core = { version = "0.6.2", optional = true }
serde = "1.0.137"
serde_with = "1.13.0"
serde_json = "1.0.80"
serde_yaml = "0.8.23"
serde_qs = "0.9.2"
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "postgres", "json", "chrono"] }
thiserror = "1.0.31"
tokio = { version = "1.18.1", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.3.2", features = ["cors", "trace"] }
tracing = "0.1.34"
tracing-subscriber = { version="0.3.11", features = ["env-filter"] }
url = { version = "2.2.2", features = ["serde"] }
uuid = { version = "1.0.0", features = ["serde", "v4"] }

ogcapi_types = { path = "../ogcapi-types" }
ogcapi_drivers = { path = "../ogcapi-drivers" }

[dev-dependencies]
geojson = "0.22.3"
ogcapi = { path = "../ogcapi" }
