[package]
name = "ogcapi-services"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[features]
default = ["common"]
full = ["default", "features", "edr", "processes", "styles", "tiles", "stac"]
common = []
features = []
edr = ["ogcapi-types/edr"]
processes = ["schemars"]
styles = []
tiles = []
stac = ["ogcapi-types/stac", "ogcapi-drivers/stac"]

[dependencies]
anyhow = "1.0.57"
axum = { version = "0.5.6", features = ["headers"] }
clap = { version = "3.1.17", features = ["derive", "env"] }
dotenv = "0.15.0"
hyper = { version = "0.14.19", features = ["full"] }
once_cell = "1.12.0"
openapiv3 = "1.0.1"
schemars = { version = "0.8.10", optional = true }
serde = "1.0.137"
serde_json = "1.0.81"
serde_yaml = "0.8.24"
serde_qs = "0.9.2"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.3.3", features = ["compression-gzip", "catch-panic", "cors", "request-id", "sensitive-headers", "trace"] }
tracing = "0.1.34"
tracing-subscriber = { version="0.3.11", features = ["env-filter"] }
url = { version = "2.2.2", features = ["serde"] }

ogcapi-types = { path = "../ogcapi-types" }
ogcapi-drivers = { path = "../ogcapi-drivers", features = ["postgres"] }

[dev-dependencies]
geojson = "0.22.4"
uuid = { version = "1.1.0", features = ["serde", "v4"] }

ogcapi = { path = "../ogcapi" }
