name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup compose
        run: docker-compose up -d db db-migrations cli 

      - name: Format
        run: docker exec -i ogcapi cargo fmt --all -- --check
      
      - name: Clippy
        run: docker exec -i ogcapi cargo clippy -- -D warnings

      - name: Test
        run: docker exec -i ogcapi cargo test --workspace
